const A = {
    ADD_WORD: 'ADD_WORD',
    UPDATE_WORD_KOREAN: 'UPDATE_WORD_KOREAN',
    UPDATE_WORD_TRANSLATION: 'UPDATE_WORD_TRANSLATION',
    DELETE_WORD: 'DELETE_WORD',
    DELETE_ALL_WORD: "DELETE_ALL_WORD",
    SHOW_KOREAN: "SHOW_KOREAN",
    SHOW_TRANSLATION: "SHOW_TRANSLATION",
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
    SEARCH: "SEARCH"
};

export { A };