const A = {
    ADD_WORD: 'ADD_WORD',
    EDIT_WORD_KOREAN: 'EDIT_WORD_KOREAN',
    EDIT_WORD_TRANSLATION: 'EDIT_WORD_TRANSLATION',
    DELETE_WORD: 'DELETE_WORD',
    DELETE_ALL_WORD: "DELETE_ALL_WORD"
};

export { A };